[project]
name = "first-steps-fastapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.3.0",
    "psycopg2-binary>=2.9.11",
]
